---
apiVersion: v1
kind: Service
metadata:
  name: location-grpc-service
  labels:
    service: location-grpc-service
spec:
  type: NodePort
  selector:
    service: location-grpc-service
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
      nodePort: 30005

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-grpc-service
  labels:
    service: location-grpc-service
spec:
  replicas: 1
  selector:
    matchLabels:
      service: location-grpc-service
  template:
    metadata:
      labels:
        service: location-grpc-service
    spec:
      containers:
        - name: location-grpc-service
          # Replace the placeholder below with your actual Docker Hub image
          image: omarkhalil10/location-service-grpc:latest
          imagePullPolicy: Always
          env:
            - name: TOPIC_NAME
              valueFrom:
                configMapKeyRef:
                  name: kafka-env
                  key: TOPIC_NAME
            - name: KAFKA_SERVER
              valueFrom:
                configMapKeyRef:
                  name: kafka-env
                  key: KAFKA_SERVER
      restartPolicy: Always
