---
apiVersion: v1
kind: Service
metadata:
  name: person-service
  labels:
    service: person-service
spec:
  type: NodePort
  selector:
    service: person-service
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
      nodePort: 30002

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: person-service
  labels:
    service: person-service
spec:
  replicas: 1
  selector:
    matchLabels:
      service: person-service
  template:
    metadata:
      labels:
        service: person-service
    spec:
      restartPolicy: Always
      containers:
        - name: person-service
          image: omarkhalil10/person-service:latest
          imagePullPolicy: Always
          env:
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_NAME
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_PORT
